#pragma once

namespace flux {
	/* See also: https://easings.net */
	enum Easing {
		EASE_LINEAR,
		EASE_QUADIN,
		EASE_QUADOUT,
		EASE_QUADINOUT,
		EASE_CUBICIN,
		EASE_CUBICOUT,
		EASE_CUBICINOUT,
		EASE_QUARTIN,
		EASE_QUARTOUT,
		EASE_QUARTINOUT,
		EASE_QUINTIN,
		EASE_QUINTOUT,
		EASE_QUINTINOUT,
		EASE_EXPOIN,
		EASE_EXPOOUT,
		EASE_EXPOINOUT,
		EASE_SINEIN,
		EASE_SINEOUT,
		EASE_SINEINOUT,
		EASE_CIRCIN,
		EASE_CIRCOUT,
		EASE_CIRCINOUT,
		EASE_BACKIN,
		EASE_BACKOUT,
		EASE_BACKINOUT,
		EASE_ELASTICIN,
		EASE_ELASTICOUT,
		EASE_ELASTICINOUT
	};
}